#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_FORMAT_DEFAULT LV_COLOR_FORMAT_RGB565
#define LV_USE_PERF_MONITOR 0
#define LV_USE_LOG 0
#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_FILESYSTEM 0
#define LV_USE_CLIPBOARD 0
#define LV_USE_GPU 0
#define LV_USE_THEME_DEFAULT 1
#define LV_USE_THEME_MATERIAL 0
#define LV_USE_THEME_MONO 0
#define LV_USE_THEME_SIMPLE 0
#define LV_USE_LABEL 1
#define LV_USE_BTN 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_MEM_SIZE (64U * 1024U)
#define LV_MEM_CUSTOM 0
#define LV_DISP_DEF_REFR_PERIOD 30
#define LV_INDEV_DEF_READ_PERIOD 30
#define LV_TXT_ENC 1
#define LV_DRAW_COMPLEX 1
#define LV_USE_DRAW_G2D 0
#define LV_USE_G2D 0
#define LV_USE_DRAW_SW 1

#endif
